name: CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Variables non-sensibles à déclarer dans Settings → Secrets and variables → Variables
env:
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}    # ex: "latest"
  SERVICES:   ${{ vars.SERVICES }}    # ex: "auth-service,billing-service,booking-service"

jobs:
  build-and-test:
    name: Build & Test ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson('["' + replace(env.SERVICES, ",", '","') + '"]') }}
    defaults:
      run:
        working-directory: ./apps/services/${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  docker-build-and-push:
    name: Docker: Build & Push ${{ matrix.service }}
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson('["' + replace(env.SERVICES, ",", '","') + '"]') }}
    defaults:
      run:
        working-directory: ./apps/services/${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/blobinfini-${{ matrix.service }}:${{ env.IMAGE_TAG }}
